#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # Actualizar la caché de archivos .desktop
    if [ -x /usr/bin/update-desktop-database ]; then
        update-desktop-database -q /usr/share/applications || true
    fi
    
    # Actualizar la caché de iconos
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
        gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -f /etc/udev/rules.d/99-vincebot.rules ]; then
        rm -f /etc/udev/rules.d/99-vincebot.rules || true
    fi
    if [ -x /usr/bin/udevadm ]; then
        udevadm control --reload-rules || true
        udevadm trigger || true
    fi
fi

exit 0
